name: FundMate
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - conda-forge::langchain-google-genai
  - conda-forge::openai
  - conda-forge::pdf2image
  - conda-forge::pdfplumber
  - httpx
  - langchain
  - langchain-openai
  - python-dotenv
  - python=3.10
  - loguru
  - conda-forge::pandas
  - conda-forge::pyarrow
prefix: /home/ljm/anaconda3/envs/FundMate
